### ISSUE TITLE
[request] Add filters based on regex

### ISSUE THREAD

**Issue by LMS0815** [jneilliii/OctoPrint-M117PopUp#16]
Please add the ability to filter messages based on regex expressions.

Some print jobs are flooding M117 messages I am not interested in.

e.g. M117 LAYERINDICATOR ...

**Comment by jneilliii** [comment]
Try out the version I just posted and see if that works for you.  You can install using the URL below in plugin manager.  

https://github.com/jneilliii/OctoPrint-M117PopUp/archive/0.6.2.zip

The regular expression is compared against the text after `M117 ` using [re.search](https://docs.python.org/3/library/re.html#re.search) so if the pattern is found anywhere in the message it will be excluded.  For your example above you should be able to just enter `LAYERINDICATOR` in the new option in settings. Multiple patterns should be able to be achieved using `|` like `(LAYERINDICATOR|IGNOREME)` would match LAYERINDICATOR or IGNOREME and not pop up those messages.

**Comment by LMS0815** [comment]
Woks like a charm. Thank you!
You probably need to add some help text (like the one above) to the plugin.
